### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by swiftgeek** [ieiao/ch552-serprog#1]
Thanks for writing serprog support for **CH552**

Since you are the author of serprog example I would suggest adding your name there
https://github.com/ieiao/ch554_sdcc/blob/serprog/examples/serprog/main.c#L3
Don't give credit to WCH for your own hard work 😉

[Description](https://github.com/ieiao/ch554_sdcc/blob/serprog/examples/serprog/main.c#L6) could be probably updated to reflect current state, like this:
```
* Description        : CH552 serprog implementation for use with flashrom
```

Additionally since the license of Blinkinlabs/ch554_sdcc repo is unclear, I would suggests adding in [README.md](https://github.com/ieiao/ch554_sdcc/blob/serprog/README.md) in your fork (in serprog branch)
`modifications made in this continuation project are, unless otherwise specified, licensed under Zero-Clause BSD` or maybe `3-Clause BSD`

So in case if upstream clears up their license, it would clear up for this project as well

**Comment by ieiao** [comment]
Thank you for your suggestion. I will make changes later.

**Comment by ieiao** [comment]
Changes already pushed.
